DNF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('authsystem/', include('authsystem.urls',namespace='authsystem')),
     path('product/', include('product.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authsystem/urls.py
from django.urls import path
from authsystem import views


app_name = 'authsystem'
urlpatterns = [
  
     # path('login/',views.logview),
     # path('register/',views.regview),
     path('myregister/',views.register_user,name='myregister'),
     path('login_user/',views.login_user,name='login'),
     path('logout_user/',views.logout_user,name='logout'),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'
urlpatterns = [

    path("", views.core,name='home'),
    path("aboutus/", views.aboutus,name='aboutus'),
    path("contactus/", views.contactus,name='contactus'),
    path("blog/", views.blog,name='blog'),
    path("search/", views.search,name='search'),

]

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path("", views.product,name='product'),
    path("category/<slug:val>", views.category,name='category'),
    path("productdetail/<int:id>", views.productdetail,name='productdetail'),
    path("test/", views.test,name='test'),
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from authsystem.models import CustomUser
from django.contrib.auth.decorators import login_required
from product.models import ProductItem
# Create your views here.

@login_required(login_url='authsystem:login')
def core(request):
   
    log_user = CustomUser.objects.get(pk = request.user.id)


    context = {
        'detail': log_user,
   
       
    }
    return render(request,'core/home.html',context)

def aboutus(request):
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        'detail': log_user,
    }
    return render(request,'core/aboutus.html',context) 

def contactus(request):
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        'detail': log_user,
    }
    return render(request,'core/contactus.html',context)


def blog(request):
    log_user = CustomUser.objects.get(pk = request.user.id)
    context = {
        'detail': log_user,
    }
    return render(request,'core/blog.html',context)

def search(request):
    query = request.GET.get('query','') # Use request.GET.get('query', '') to get the 'query' parameter value with a default empty string
    print(type(query))
    if not query:
        pass
    else:
        log_user = CustomUser.objects.get(pk = request.user.id)
        product = ProductItem.objects.filter(P_name__icontains=query)
        context = {
            'product': product,
            'detail': log_user,
        }
        return render(request,'core/search.html',context)
    return render(request,'core/search.html')

templates/core/aboutus.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<!-- inner page section -->
   <section class="inner_page_head">
    <div class="container_fuild">
       <div class="row">
          <div class="col-md-12">
             <div class="full">
                <h3>About us</h3>
             </div>
          </div>
       </div>
    </div>
 </section>
 <!-- end inner page section -->

 {% endblock %}

templates/core/blog.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<!-- inner page section -->
<section class="inner_page_head">
   <div class="container_fuild">
      <div class="row">
         <div class="col-md-12">
            <div class="full">
               <h3>Blog List</h3>
            </div>
         </div>
      </div>
   </div>
</section>

<div id="carouselExample3Controls" class="carousel slide" data-ride="carousel">
   <div class="carousel-inner">
      <div class="carousel-item active">
         <div class="box col-lg-10 mx-auto">
            <div class="detail-box">
               <h5>
                  <br>
                  <br>
                  Our Blog
               </h5>
               <br>
               <h6>
                  Latest Fashion Trends: Embrace Your Dark Side
               </h6>
               <br>
               <br>
               <p>
                  Stay ahead of the fashion curve with our blog,
                  where we dive into the latest trends, style tips,
                  and fashion inspiration. At Dark and Freed Clothing,
                  we believe that fashion is a dynamic art form that evolves constantly.
                  Our blog is your go-to resource for staying updated on the hottest
                  trends and discovering unique ways to express your individuality.
               </p>
               <div class="img_container">
                  <div class="img-box">
                     <div class="img_box-inner">
                        <img src="{% static '/images/c1.png' %}" height="200" width="200" alt="">
                     </div>
                  </div>
               </div>
              

               <div class="box col-lg-5 mx-auto">
               <p>

                  "Unleashing Your Inner Rebel: The Art of Edgy Fashion"
                  Explore the world of edgy fashion and learn how to incorporate bold elements into your wardrobe. From
                  leather jackets to statement accessories, discover the key pieces that define the edgy style.

                  "Alternative Fashion: Embracing Non-Conformity in Style"
                  Dive into the realm of alternative fashion, where creativity knows no limits. Find inspiration in
                  unconventional styles, unconventional fabrics, and avant-garde designs. Learn how to break free from
                  traditional fashion norms and embrace the freedom of self-expression.

                  "DIY Fashion: Personalize Your Wardrobe with Creative Hacks"
                  Get crafty with our do-it-yourself fashion tips. Learn how to transform ordinary pieces into
                  extraordinary fashion statements. From distressed jeans to customized t-shirts, discover fun and
                  inventive ways to personalize your clothing and make a statement.

                  "Fashion Icons: Celebrating Rebels and Trendsetters"
                  Delve into the lives of fashion icons who have left an indelible mark on the industry. From iconic
                  designers to rebellious celebrities, learn about the pioneers who have shaped the way we perceive
                  fashion today.

                  Stay tuned for regular updates, style guides, and insider insights into the world of edgy and
                  alternative fashion. Let your creativity run wild and redefine fashion on your terms with Dark and
                  Freed Clothing's blog.
               </p>
            </div>
            </div>

         </div>
      </div>
   </div>
</div>

<!-- end inner page section -->

{% endblock %}

templates/core/contactus.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

      <!-- inner page section -->
      <section class="inner_page_head">
        <div class="container_fuild">
           <div class="row">
              <div class="col-md-12">
                 <div class="full">
                    <h3>Contact us</h3>
                 </div>
              </div>
           </div>
        </div>
     </section>
     <!-- end inner page section -->
     <!-- why section -->
     <section class="why_section layout_padding">
        <div class="container">
        
           <div class="row">
              <div class="col-lg-8 offset-lg-2">
                 <div class="full">
                    <form action="index.html">
                       <fieldset>
                          <input type="text" placeholder="Enter your full name" name="name" required />
                          <input type="email" placeholder="Enter your email address" name="email" required />
                          <input type="text" placeholder="Enter subject" name="subject" required />
                          <textarea placeholder="Enter your message" required></textarea>
                          <input type="submit" value="Submit" />
                       </fieldset>
                    </form>
                 </div>
              </div>
           </div>
        </div>
     </section>
     <!-- end why section -->

{% endblock %}

templates/core/hf.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
   <!-- Basic -->
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   <!-- Site Metas -->
   <meta name="keywords" content="" />
   <meta name="description" content="" />
   <meta name="author" content="" />
   <link rel="shortcut icon" href="{% static '/images/l2.png' %}" type="">
   <title>DARK N FREED</title>
   <!-- bootstrap core css -->
   <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}" />
   <!-- font awesome style -->
   <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
   <!-- Custom styles for this template -->
   <link href="{% static '/css/style.css' %}" rel="stylesheet" />
   <!-- responsive style -->
   <link href="{% static '/css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

   <div class="">
      <!-- header section strats -->
      <header class="header_section">
         <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container ">

               <a class="navbar-brand" href="index.html">
                  <img width="150" style="border-radius:10%;" src="{% static '/images/l2.png' %}" alt="#" />
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class=""> </span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav">

                     {% if user.is_authenticated %}

                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
                     </li>

                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Products <span
                                 class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'product:category' 'M' %}">Man Collections</a></li>
                           <li><a href="{% url 'product:category' 'W' %}">Women Collections</a></li>
                           <li><a href="{% url 'product:category' 'A' %}">All Product</a></li>

                        </ul>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:blog' %}">Blog</a>
                     </li>

                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:aboutus' %}">AboutUs</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:contactus' %}">Contact</a>
                     </li>
                     <form method="GET" action="{% url 'core:search' %}" class="form-inline">
                        <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search product"
                           aria-label="Search">
                        <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                           <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
                        </button>
                     </form>




                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label"> {{ detail.first_name }}
                              <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'authsystem:login' %}">Logout</a></li>

                        </ul>
                     </li>
                     {% endif %}
                     {% if not user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:myregister' %}">Register</a>
                     </li>
                     {% endif %}
                  </ul>
               </div>
            </nav>
         </div>
      </header>
      <!-- end header section -->
   </div>



   {% block body %}

   {% endblock %}




   <!-- footer start -->
   <footer>
      <div class="container">
         <div class="row">
            <div class="col-md-4">
               <div class="full">
                  <div class="logo_footer">
                     <a href="#"><img width="210" style="border-radius:10%;" src="{% static '/images/l2.png' %}"
                           alt="#" /></a>
                  </div>
                  <div class="information_f">
                     <p><strong>ADDRESS:</strong> Comming Soon...</p>
                     <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                     <p><strong>EMAIL:</strong> darknfreed23@gmail.com</p>
                  </div>
               </div>
            </div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Menu</h3>
                              <ul>
                                 <li><a href="#">Home</a></li>
                                 <li><a href="#">About</a></li>
                                 <li><a href="#">Services</a></li>
                                 <li><a href="#">Testimonial</a></li>
                                 <li><a href="#">Blog</a></li>
                                 <li><a href="#">Contact</a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Account</h3>
                              <ul>
                                 <li><a href="#">Account</a></li>
                                 <li><a href="#">Checkout</a></li>
                                 <li><a href="#">Login</a></li>
                                 <li><a href="#">Register</a></li>
                                 <li><a href="#">Shopping</a></li>

                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                           <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form>
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" name="email" />
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </footer>
   <!-- footer end -->
   <div class="cpy_">
      <p>© 2023 All Rights Reserved By</a></p>
   </div>
   <!-- jQery -->
   <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
   <!-- popper js -->
   <script src="{% static '/js/popper.min.js' %}"></script>
   <!-- bootstrap js -->
   <script src="{% static '/js/bootstrap.js' %}"></script>
   <!-- custom js -->
   <script src="{% static '/js/custom.js' %}"></script>





</body>

</html>

templates/core/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
   <!-- Basic -->
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   <!-- Site Metas -->
   <meta name="keywords" content="" />
   <meta name="description" content="" />
   <meta name="author" content="" />
   <link rel="shortcut icon" href="{% static '/images/l2.png' %}" type="">
   <title>DARK N FREED</title>
   <!-- bootstrap core css -->
   <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}" />
   <!-- font awesome style -->
   <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
   <!-- Custom styles for this template -->
   <link href="{% static '/css/style.css' %}" rel="stylesheet" />
   <!-- responsive style -->
   <link href="{% static '/css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

   <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
         <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container ">

               <a class="navbar-brand" href="index.html">
                  <img width="150" style="border-radius:10%;" src="{% static '/images/l2.png' %}" alt="#" />
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class=""> </span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav">

                     {% if user.is_authenticated %}

                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
                     </li>

                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Products <span
                                 class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'product:category' 'M' %}">Man Collections</a></li>
                           <li><a href="{% url 'product:category' 'W' %}">Women Collections</a></li>
                           <li><a href="{% url 'product:category' 'A' %}">All Product</a></li>

                        </ul>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:blog' %}">Blog</a>
                     </li>

                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:aboutus' %}">AboutUs</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:contactus' %}">Contact</a>
                     </li>
                     <form method="GET" action="{% url 'core:search' %}" class="form-inline">
                        <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search product"
                           aria-label="Search">
                        <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                           <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
                        </button>
                     </form>




                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="true"> <span class="nav-label"> {{ detail.first_name }}
                              <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'authsystem:login' %}">Logout</a></li>

                        </ul>
                     </li>
                     {% endif %}
                     {% if not user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'authsystem:myregister' %}">Register</a>
                     </li>
                     {% endif %}
                  </ul>
               </div>
            </nav>
         </div>
      </header>
      <!-- end header section -->

      <!-- slider section -->
      <section class="slider_section ">
         <div class="slider_bg_box">
            <img src="{% static '/images/banner.png' %}" alt="">
         </div>
         <div id="customCarousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 10% Off
                                 </span>
                                 <br>
                                 On T-Shirts
                              </h1>
                              <p>
                                 Attention, fashion enthusiasts! We are thrilled to introduce our latest offer that adds
                                 a touch of style to your wardrobe without breaking the bank. It’s the perfect
                                 opportunity to upgrade your fashion game without compromising your budget. </p>
                              <div class="btn-box">
                                 <a href="" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item ">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 20% Off
                                 </span>
                                 <br>
                                 On Hoddies
                              </h1>
                              <p>
                                 This season, embrace the chill in style with our exclusive hoodie collection, now
                                 available at a fabulous 20% discount! Snuggle up in our high-quality, trendy hoodies.
                                 Hurry, the offer won’t last long. Grab your favorite hoodie today and step out in
                                 comfort and confidence!
                              <div class="btn-box">
                                 <a href="" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container ">
                     <div class="row">
                        <div class="col-md-7 col-lg-6 ">
                           <div class="detail-box">
                              <h1>
                                 <span>
                                    Sale 10% Off
                                 </span>
                                 <br>
                                 for New User
                              </h1>
                              <p>
                                 We're thrilled to have you on board! As a token of our appreciation, all new users can
                                 enjoy an exclusive 10% discount on their first purchase. Dive into our diverse range of
                                 products, find your favorites, and let the savings begin. Happy shopping! </p>
                              <div class="btn-box">
                                 <a href="" class="btn1">
                                    Shop Now
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="container">
               <ol class="carousel-indicators">
                  <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
                  <li data-target="#customCarousel1" data-slide-to="1"></li>
                  <li data-target="#customCarousel1" data-slide-to="2"></li>
               </ol>
            </div>
         </div>
      </section>
      <!-- end slider section -->
   </div>



   {% block body %}

   {% endblock %}




   <!-- footer start -->
   <footer>
      <div class="container">
         <div class="row">
            <div class="col-md-4">
               <div class="full">
                  <div class="logo_footer">
                     <a href="#"><img width="210" style="border-radius:10%;" src="{% static '/images/l2.png' %}"
                           alt="#" /></a>
                  </div>
                  <div class="information_f">
                     <p><strong>ADDRESS:</strong> Comming Soon...</p>
                     <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                     <p><strong>EMAIL:</strong> darknfreed23@gmail.com</p>
                  </div>
               </div>
            </div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Menu</h3>
                              <ul>
                                 <li><a href="#">Home</a></li>
                                 <li><a href="#">About</a></li>
                                 <li><a href="#">Services</a></li>
                                 <li><a href="#">Testimonial</a></li>
                                 <li><a href="#">Blog</a></li>
                                 <li><a href="#">Contact</a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="widget_menu">
                              <h3>Account</h3>
                              <ul>
                                 <li><a href="#">Account</a></li>
                                 <li><a href="#">Checkout</a></li>
                                 <li><a href="#">Login</a></li>
                                 <li><a href="#">Register</a></li>
                                 <li><a href="#">Shopping</a></li>

                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                           <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form>
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" name="email" />
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </footer>
   <!-- footer end -->
   <div class="cpy_">
      <p>© 2023 All Rights Reserved By</a></p>
   </div>
   <!-- jQery -->
   <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
   <!-- popper js -->
   <script src="{% static '/js/popper.min.js' %}"></script>
   <!-- bootstrap js -->
   <script src="{% static '/js/bootstrap.js' %}"></script>
   <!-- custom js -->
   <script src="{% static '/js/custom.js' %}"></script>





</body>

</html>