DNF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('authsystem/', include('authsystem.urls',namespace='authsystem')),
     path('product/', include('product.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path("", views.product,name='product'),
    path("category/<slug:val>", views.category,name='category'),
    path("productdetail/<int:id>", views.productdetail,name='productdetail'),
    path("test/", views.test,name='test'),
    
]

product/models.py
from django.db import models

# Create your models here.

CATAGORY_CHOICES = (
    ('M','Mens'),
    ('W','Womens'),
    ('A','All')
)


class ProductItem(models.Model):
    
    P_name = models.CharField(max_length=100)
    P_Qty = models.IntegerField()
    P_Price = models.FloatField(max_length=15)
    CATAGORY_CHOICES = models.CharField(max_length=1, choices=CATAGORY_CHOICES, default='A')
    P_Image = models.ImageField(upload_to='image', blank=True, null=True)
    # R1_Image = models.ImageField(upload_to='image', blank=True, null=True)
    # R2_Image = models.ImageField(upload_to='image', blank=True, null=True)
    P_Desc = models.CharField(max_length=1000)
    # P_Discount = models.FloatField(max_length=15)
    #customer_id = models.ForeignKey('Customer',on_delete=models.CASCADE)
    
    def get_image_url(self):
        return f"{self.P_Image.url}"
    
    def get_image_url(self):
        return f"{self.R1_Image.url}"
    
    def get_image_url(self):
        return f"{self.R2_Image.url}"
    
    def __str__(self):
        return f"{self.P_name}"
    


    

product/views.py
from django.shortcuts import render
from product.models import ProductItem
from django.http import HttpResponse


# Create your views here.
def product(request):

    product = ProductItem.objects.all()
    context = {
        'product': product
    }
    return render(request, 'product/product.html',context)


def category(request, val):

    product = ProductItem.objects.filter(CATAGORY_CHOICES=val)
    title = ProductItem.objects.filter(CATAGORY_CHOICES=val).values('P_name')
    context = {
        'val': val,
        'product': product,
        'title': title,
    }
    return render(request, 'product/category.html', context)

def productdetail(request, id):
    pro = ProductItem.objects.get(pk=id)
    context = {
        'pro': pro
    }

    return render(request, 'product/productdetail.html',context)

def test(request):
   return render(request, 'product/test.html')

templates/product/category.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}
<!-- <h1>category {{product}} {{title}}</h1>

<div class="container">
    {% for v in title %}
        <h1>{{v.P_name}}</h1>
    {% endfor %}
</div> -->

    <!-- inner page section -->
    <section class="inner_page_head">
        <div class="container_fuild">
           <div class="row">
              <div class="col-md-12">
                 <div class="full">
                    <h3>Product Grid</h3>
                 </div>
              </div>
           </div>
        </div>
     </section>
     <!-- end inner page section -->
     <!-- product section -->
     <section class="product_section layout_padding">
        <div class="container">
           <div class="heading_container heading_center">
              <h2>
                 Our <span>products</span>
              </h2>
           </div>
           <div class="row">
                {% for p in product %}
              <div class="col-sm-6 col-md-4 col-lg-3">
                 <div class="box">
                    <div class="option_container">
                       <div class="options">
                          <a href="{% url 'product:productdetail' id=p.pk %}" class="option1">
                          View Product
                          </a>
                          <a href="" class="option2">
                          Buy Now
                          </a>
                       </div>
                    </div>
                    <div class="img-box">
                       <img src="{{p.P_Image.url}}" alt="">
                    </div>
                    

                     <div class="detail-box">
                        <h5>
                         {{p.P_name}}
                        </h5>
                        
                     </div>
                     <div class="detail-box">
                         
                         <h6>
                            {{p.P_Price}}
                         </h6>
                      </div>
                 </div>
              </div>
              {% endfor %}
           
              
              <!-- <div class="col-sm-6 col-md-4 col-lg-3">
                 <div class="box">
                    <div class="option_container">
                       <div class="options">
                          <a href="" class="option1">
                          Add To Cart
                          </a>
                          <a href="" class="option2">
                          Buy Now
                          </a>
                       </div>
                    </div>
                    <div class="img-box">
                       <img src="images/p2.png" alt="">
                    </div>
                    <div class="detail-box">
                       <h5>
                          Men's Shirt
                       </h5>
                       <h6>
                          $80
                       </h6>
                    </div>
                 </div>
              </div>
              
              
              <div class="col-sm-6 col-md-4 col-lg-3">
                 <div class="box">
                    <div class="option_container">
                       <div class="options">
                          <a href="" class="option1">
                          Add To Cart
                          </a>
                          <a href="" class="option2">
                          Buy Now
                          </a>
                       </div>
                    </div>
                    <div class="img-box">
                       <img src="images/p12.png" alt="">
                    </div>
                    <div class="detail-box">
                       <h5>
                          Women's Dress
                       </h5>
                       <h6>
                          $65
                       </h6>
                    </div>
                 </div>
              </div> -->
           </div>
           <div class="btn-box">
              <a href="">
              View All products
              </a>
           </div>
        </div>
     </section>
     <!-- end product section -->




{% endblock %}

templates/product/product.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

    <!-- inner page section -->
    <section class="inner_page_head">
        <div class="container_fuild">
           <div class="row">
              <div class="col-md-12">
                 <div class="full">
                    <h3>Product Grid</h3>
                 </div>
              </div>
           </div>
        </div>
     </section>
     <!-- end inner page section -->
     <!-- product section -->
     <section class="product_section layout_padding">
        <div class="container">
           <div class="heading_container heading_center">
              <h2>
                 Our <span>products</span>
              </h2>
           </div>
           <div class="row">
                {% for prod in product %}
              <div class="col-sm-6 col-md-4 col-lg-3">
                 <div class="box">
                    <div class="option_container">
                       <div class="options">
                          <a href="#" class="option1">
                          Addto Shirt
                          </a>
                          <a href="" class="option2">
                          Buy Now
                          </a>
                       </div>
                    </div>
                    <div class="img-box">
                       <img src="{{prod.P_Image.url}}" alt="">
                    </div>
                    

                     <div class="detail-box">
                        <h5>
                         {{prod.P_name}}
                        </h5>
                        
                     </div>
                     <div class="detail-box">
                         
                         <h6>
                            {{prod.P_Price}}
                         </h6>
                      </div>
                 </div>
              </div>
              {% endfor %}
           
              
              <!-- <div class="col-sm-6 col-md-4 col-lg-3">
                 <div class="box">
                    <div class="option_container">
                       <div class="options">
                          <a href="" class="option1">
                          Add To Cart
                          </a>
                          <a href="" class="option2">
                          Buy Now
                          </a>
                       </div>
                    </div>
                    <div class="img-box">
                       <img src="images/p2.png" alt="">
                    </div>
                    <div class="detail-box">
                       <h5>
                          Men's Shirt
                       </h5>
                       <h6>
                          $80
                       </h6>
                    </div>
                 </div>
              </div>
              
              
              
           </div>
           <div class="btn-box">
              <a href="">
              View All products
              </a>
           </div>
        </div>
     </section>
     <!-- end product section -->






{% endblock %}

templates/product/productdetail.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}

<!-- inner page section -->
<section class="inner_page_head">
    <div class="container_fuild">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <h3>Product Detail</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end inner page section -->
<!-- product section -->
<section class="product_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="box">
                    <div class="option_container">

                    </div>
                    <div class="img-box">
                        <img src="{{pro.P_Image.url}}" alt="">
                    </div>

                    <div class="detail-box">
                        <h5>
                            {{pro.P_name}}
                        </h5>
                    </div>
                    <div class="detail-box">
                        <h6>
                            {{pro.P_Price}}
                        </h6>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="product-details">
                    <h2>{{ pro.P_name }}</h2>
                    <p>{{ pro.P_Desc }}</p>
                    <b><p>Price: </b>{{ pro.P_Price }}</p>
                    <label for="size"><b>Select Size:</b></label>
                    <select id="size" name="size">
                        <option value="small">Small</option>
                        <option value="medium">Medium</option>
                        <option value="large">Large</option>
                    </select>
                    <div class="btn-box">
                        
                    <button type="button" style="background-color: #f7444e;">Add to Cart</button>
                    <button type="button" style="background-color: #f7444e;">Add to Wishlist</button>
                    <button type="button" style="background-color: #f7444e;">Buy Now</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- <div class="btn-box">
        <a href="">
            View All products
        </a>
    </div> -->
</section>

<style>
    .product_section {
        padding: 50px 0;
    }

    .box {
        display: flex;
        flex-direction: column;
        height: 100%; /* Make the box take full height */
    }

    .img-box {
        flex: 1; /* Allow the image box to take the available space */
    }

    .img-box img {
        max-width: 100%;
        height: auto;
    }

    .product-details {
        padding: 20px;
        box-sizing: border-box;
        height: 100%; /* Make the details box take full height */
    }

    .product-details h2 {
        margin-top: 0;
    }

    .product-details p {
        margin-bottom: 15px;
    }

    .product-details label {
        display: block;
        margin-bottom: 5px;
    }

    .product-details select {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        font-size: 16px;
    }

    .product-details button {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 5px;
        margin-right: 10px;
    }

    .product-details button:hover {
        background-color: #0056b3;
    }

    .btn-box {
        margin-top: 20px;
    }
</style>

{% endblock %}

templates/product/test.html
{% extends 'core/hf.html' %}
{% load static %}

{% block body %}
    <!-- product details section -->
    <section class="product-details-section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="product-image">
                        <img src="{{ product.P_Image.url }}" alt="{{ product.P_name }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="product-details">
                        <h2>{{ product.P_name }}</h2>
                        <p>{{ product.P_Description }}</p>
                        <p>Price: {{ product.P_Price }}</p>
                        <label for="size">Select Size:</label>
                        <select id="size" name="size">
                            <option value="small">Small</option>
                            <option value="medium">Medium</option>
                            <option value="large">Large</option>
                        </select>
                        <button type="button" onclick="addToCart()">Add to Cart</button>
                        <button type="button" onclick="addToWishlist()">Add to Wishlist</button>
                        <button type="button" onclick="buyNow()">Buy Now</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end product details section -->
{% endblock %}